import { useState } from "react";

const STACK = [
  ["Retrieval", "Qdrant vector search over ingested agricultural and climate documents"],
  ["Reranking", "Jina reranker, to sort retrieved chunks by actual relevance to the query"],
  ["Generation", "Groq, constrained to write only from retrieved evidence"],
  ["Structured data", "Supabase — species profiles and environmental records"],
  ["Environmental lookups", "SoilGrids and Sentinel-2 (both via Google Earth Engine), plus NASA POWER (temperature, rainfall) — fetched live on a cache miss"],
];

const STRENGTHS = [
  {
    title: "Grounded, not guessed",
    detail:
      "Every answer traces back to retrieved evidence. When retrieval doesn't turn up enough to support a claim, the system says so directly instead of producing something plausible-sounding.",
  },
  {
    title: "Hybrid retrieval",
    detail:
      "Combines dense vector search (Jina embeddings + Qdrant) with BM25 keyword search, fused by reciprocal rank fusion — so an exact species name or figure isn't missed just because semantic search alone didn't weight it heavily.",
  },
  {
    title: "Hyperlocal focus",
    detail:
      "Built around Mandi Bahauddin's actual climate classification, soil chemistry, and flood-risk research, rather than general-purpose plant advice tuned for a global audience.",
  },
  {
    title: "Live, per-point environmental data",
    detail:
      "Soil, temperature, rainfall, and vegetation indices are fetched for the exact coordinates you select — not a district-wide average — and cached so repeat lookups are fast.",
  },
  {
    title: "Traceable citations",
    detail:
      "Every source shown to you comes from the retrieved document's own metadata — title, year, URL — never generated by the model. A citation can't be fabricated by construction.",
  },
];

const LIMITATIONS = [
  {
    title: "Evidence is district-level, not per-point",
    detail:
      "Retrieved documents aren't geo-tagged to specific coordinates within Mandi Bahauddin. Two different map clicks will show different environmental numbers but draw on the same retrieved evidence.",
  },
  {
    title: "Climate data resolution is coarser than the district",
    detail:
      "NASA POWER's native grid (roughly 55 x 70 km) is larger than all of Mandi Bahauddin, so temperature and rainfall figures read the same across the whole district rather than varying block to block.",
  },
  {
    title: "Coverage depends entirely on what's been ingested",
    detail:
      "A well-formed question outside the ingested research papers correctly returns \"insufficient evidence,\" not a general-knowledge answer — the system won't fill genuine gaps in its own reading list.",
  },
  {
    title: "Live data has a real dependency",
    detail:
      "Some environmental sources (Sentinel-2 and SoilGrids via Google Earth Engine) need an authenticated service account. If that authentication lapses, those specific fields fall back to \"not available,\" not an estimate.",
  },
  {
    title: "An unusual figure is still reported, not discarded",
    detail:
      "If a source paper contains an outlier value, it's cited exactly as published rather than smoothed over — the answer will try to flag it as unusual where the evidence supports that, but it won't quietly drop it.",
  },
];

function ExpandableList({ items, accent }) {
  const [openIndex, setOpenIndex] = useState(null);

  const markerClass = accent === "warning" ? "bg-warning" : "bg-accent";

  return (
    <ul className="mt-3 divide-y divide-bark-500/10 rounded-lg border border-bark-500/15 bg-card/50">
      {items.map((item, i) => {
        const isOpen = openIndex === i;
        return (
          <li key={item.title}>
            <button
              type="button"
              onClick={() => setOpenIndex(isOpen ? null : i)}
              aria-expanded={isOpen}
              className="flex w-full items-center gap-3 px-4 py-3 text-left transition hover:bg-panel/60"
            >
              <span className={`h-1.5 w-1.5 shrink-0 rounded-full ${markerClass}`} aria-hidden="true" />
              <span className="flex-1 text-sm font-medium text-soil-900">{item.title}</span>
              <svg
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                className={`h-4 w-4 shrink-0 text-bark-500 transition-transform duration-fast ${
                  isOpen ? "rotate-180" : ""
                }`}
                aria-hidden="true"
              >
                <path d="M6 9l6 6 6-6" />
              </svg>
            </button>
            {isOpen && (
              <p className="px-4 pb-3 pl-[34px] text-sm text-bark-700">{item.detail}</p>
            )}
          </li>
        );
      })}
    </ul>
  );
}

export default function About() {
  return (
    <div className="mx-auto max-w-2xl px-4">
      <h1 className="font-[var(--font-display)] text-2xl font-semibold text-soil-900">About this project</h1>
      <p className="mt-3 text-soil-900">
        This is a location-aware recommendation system for climate-resilient tree plantation in Mandi Bahauddin,
        Punjab, Pakistan — built as an AI Engineering final year project. It answers questions about tree species,
        soil, water, and climate for the district, and pairs every recommendation with the environmental data and
        source documents behind it.
      </p>

      <h2 className="mt-8 font-[var(--font-display)] text-lg font-semibold text-soil-900">
        How this avoids guessing
      </h2>
      <p className="mt-2 text-soil-900">
        The system is built around a simple constraint: it should never answer beyond what its evidence supports.
        Every query first goes through retrieval, so an answer is written only from the documents that were
        actually found — not from general knowledge. Sources are cited rather than paraphrased freely, so a claim
        can always be traced back to where it came from. And when retrieval doesn't turn up enough to support an
        answer, the system says so directly instead of producing something plausible-sounding — that's the
        <code className="mx-1 rounded bg-bark-500/10 px-1.5 py-0.5 text-sm">evidence_available: false</code>
        state you'll see in the AI Assistant.
      </p>

      <h2 className="mt-8 font-[var(--font-display)] text-lg font-semibold text-soil-900">Strengths</h2>
      <p className="mt-2 text-sm text-bark-700">Tap an item for detail.</p>
      <ExpandableList items={STRENGTHS} accent="accent" />

      <h2 className="mt-8 font-[var(--font-display)] text-lg font-semibold text-soil-900">Architecture</h2>
      <dl className="mt-3 divide-y divide-bark-500/10 rounded-lg border border-bark-500/15 bg-card/50">
        {STACK.map(([label, description]) => (
          <div key={label} className="grid grid-cols-[140px_1fr] gap-4 px-4 py-3">
            <dt className="text-sm text-bark-700">{label}</dt>
            <dd className="text-sm text-soil-900">{description}</dd>
          </div>
        ))}
      </dl>

      <h2 className="mt-8 font-[var(--font-display)] text-lg font-semibold text-soil-900">Scope</h2>
      <p className="mt-2 text-soil-900">
        The knowledge base and environmental lookups are scoped to Mandi Bahauddin district. Recommendations
        outside that area, or on topics the knowledge base hasn't ingested yet, will come back as
        "no evidence found" rather than a generic answer.
      </p>

      <h2 className="mt-8 font-[var(--font-display)] text-lg font-semibold text-soil-900">Limitations</h2>
      <p className="mt-2 text-sm text-bark-700">Stated plainly, on purpose — tap an item for detail.</p>
      <ExpandableList items={LIMITATIONS} accent="warning" />

      <h2 className="mt-8 font-[var(--font-display)] text-lg font-semibold text-soil-900">Frontend stack</h2>
      <p className="mt-2 text-soil-900">React, Vite, Tailwind CSS, React-Leaflet, and Axios.</p>
    </div>
  );
}